### ISSUE TITLE
OCSP falure's

### ISSUE THREAD

**Issue by jalonet** [matteocorti/check_ssl_cert#32]
Seeing "Unable to fetch OCSP issuer certificate." when checking a working domain.

Looks like the latest Centos 7 "file" command will recognise a PEM file so "file cert.crt" returns "cert.crt: PEM certificate" instead of "cert.crt: ASCII text". So some OCSP checks will fail.

Quick workaround is to change 
        # check the result
        if ! file "${ISSUER_CERT}" | grep -q ': ASCII' ; then
to
        # check the result
        if ! file "${ISSUER_CERT}" | grep -q ': \(ASCII\|PEM\)' ; then

**Comment by matteocorti** [comment]
Fixed in 1.36

**Comment by ckrey** [comment]
Hi @matteocorti , this doesn't seem to fix the problem (letscencrypt cert):

140621798745928:error:27076072:OCSP routines:PARSE_HTTP_LINE1:server response error:ocsp_ht.c:250:Code=400,Reason=Bad Request|days=78;;;;

**Comment by matteocorti** [comment]
Hi
can you give me an example so that I can test?
