### ISSUE TITLE
validate certificate chain of local certificate

### ISSUE THREAD

**Issue by ctriegg-mak** [matteocorti/check_ssl_cert#325]
**Is your feature request related to a problem? Please describe.**

We want to validate our `crt` files (certificate + intermediate). This turns out to be surprisingly difficult. 

**Describe the solution you'd like**

At the moment the `-f` parameter is supported. The certificates in this file are checked for `ocsp` and expiration. It would be great if the chain could be validated too. 

**Describe alternatives you've considered**

We seriously thought about build pipelines installing the certificate in a container and check it via `check_ssl_cert`. But this seems to be a bit of overengineering. 

**Additional context**

I'm happy to help. But at the moment I'm not sure where to start in the script. I think the `crt` file containing the signed certificate and the intermediates have to be seperated to check it via `openssl`. Is this even a desired feature?

**Comment by ctriegg-mak** [comment]
Hi. Sorry for the late reply. 

I try to make up an example: 

When deploying a certificate for nginx usually a file containing the certificate chain is deployed. If one of the intermediate certificates is missing there is a problem (which would be alerted via our nagios checks using `check_ssl_cert`). But I would like to prevent the deployment of a certificate with a missing intermediate certificate. I thought I could check the certificate with the `-f` parameter but it seems that there is no verification if the chain is complete. 

Looking at the SSL certificate of google.com (fetched certificate via `openssl s_client -showcerts -servername google.com -connect google.com:443`) you can see the chain elements. I would expected that if i store these elements in a file and execute a check with `-f` it's fine. If I remove the chain elements the check should fail. 

I hope that helps :sweat_smile:

**Comment by matteocorti** [comment]
Thank I get your point. I'll see what I can do.

**Comment by matteocorti** [comment]
Thanks for the coffee :-)
I'll take a look (with my tests a missing element should trigger a critical)

**Comment by matteocorti** [comment]
I committed a fix that seems to work. Can you please test?

**Comment by ctriegg-mak** [comment]
I'm still having issues. But i have figured out a way to fix it. 

I will provide a PR as soon.
